### ISSUE TITLE
more tasteful docs

### ISSUE THREAD

**Issue by andrewdamelio** [halt-hammerzeit/require-hacker#3]
Anyway you can update/remove the **Something unusual** doc example - i'm sure you can think of something more appropriate. If you want, I can submit a PR.

**Comment by halt-hammerzeit** [comment]
Hello.
I'm not native english.
Is there something wrong with the stylistics of the readme?

**Comment by andrewdamelio** [comment]
Hi Halt,
Your english is perfect!

Its more so the use of xhamster as a example, I personally think this is a little gross. 

I could also see this being a barrier for people who may otherwise want to help contribute or use this.

**Comment by halt-hammerzeit** [comment]
Oh, I see.
Well, I always thought that they wrote in the newspapers that it's tyranny in Russia and Putin is dictator because he prohibits gay parades and such.
I always thought the western society is progressive in this sense: they have gay parades, even gay marriages. They care for such thing very much I thought.
Anyway, I got your point. But I think there's too little fun on github so let's put some lights on. He he. Why so seriousss?

**Comment by halt-hammerzeit** [comment]
Btw I dig lesbians and schoolgirls (16 and older).

**Comment by halt-hammerzeit** [comment]
(forgot about feet, I like feet too)
